<footer>
        <div class="row bg-3">
            <div class="col-lg-6">
                <br/>
                Copyright &copy; Team wingtech 2017
            </div>

            <div class="col-lg-4 col-lg-offset-2">
                <ul class="list-inline intro-buttons">
                    <li>
                        <a href="#" class="btn btn-default btn-lg footer-btn" id="logIn">Log In <i
                                class="fa fa-arrow-right fa-fw"></i></a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-default btn-lg footer-btn" id="register">Register <i
                                class="fa fa-arrow-right fa-fw"></i></a>
                    </li>

                </ul>

            </div>
            <div class="text-center">
                <h6>Coded with <i class="fa fa-heart red"></i> at WINGTECH</a></h6>
            </div>
        </div>
    </footer>