 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Bootstrap Core CSS -->
    <link href="assets/libs/bootstrap.min/index.css" rel="stylesheet">
    <link href="assets/libs/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<!--Animate CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet">
	<!--Hover CSS-->
	<link href="assets/css/hover-min.css" rel="stylesheet">
	<!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Dosis|Reem+Kufi|Trirong"
          rel="stylesheet">
		  